// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/admin/applications": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/community": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/join": {
    params: {};
  };
  "/lessons": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/scan/:token": {
    params: {
      "token": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/account/logout" | "/account/signin" | "/account/signup" | "/admin/applications" | "/admin/users" | "/community" | "/contact" | "/faq" | "/forgot-password" | "/gallery" | "/join" | "/lessons" | "/reset-password" | "/resources" | "/scan/:token" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./about/page.jsx": {
    id: "about/page";
    page: "/about";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./admin/applications/page.jsx": {
    id: "admin/applications/page";
    page: "/admin/applications";
  };
  "./admin/users/page.jsx": {
    id: "admin/users/page";
    page: "/admin/users";
  };
  "./community/page.jsx": {
    id: "community/page";
    page: "/community";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./faq/page.jsx": {
    id: "faq/page";
    page: "/faq";
  };
  "./forgot-password/page.jsx": {
    id: "forgot-password/page";
    page: "/forgot-password";
  };
  "./gallery/page.jsx": {
    id: "gallery/page";
    page: "/gallery";
  };
  "./join/page.jsx": {
    id: "join/page";
    page: "/join";
  };
  "./lessons/page.jsx": {
    id: "lessons/page";
    page: "/lessons";
  };
  "./reset-password/page.jsx": {
    id: "reset-password/page";
    page: "/reset-password";
  };
  "./resources/page.jsx": {
    id: "resources/page";
    page: "/resources";
  };
  "./scan/[token]/page.jsx": {
    id: "scan/[token]/page";
    page: "/scan/:token";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "about/page": typeof import("./src/app/./about/page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "admin/applications/page": typeof import("./src/app/./admin/applications/page.jsx");
  "admin/users/page": typeof import("./src/app/./admin/users/page.jsx");
  "community/page": typeof import("./src/app/./community/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "faq/page": typeof import("./src/app/./faq/page.jsx");
  "forgot-password/page": typeof import("./src/app/./forgot-password/page.jsx");
  "gallery/page": typeof import("./src/app/./gallery/page.jsx");
  "join/page": typeof import("./src/app/./join/page.jsx");
  "lessons/page": typeof import("./src/app/./lessons/page.jsx");
  "reset-password/page": typeof import("./src/app/./reset-password/page.jsx");
  "resources/page": typeof import("./src/app/./resources/page.jsx");
  "scan/[token]/page": typeof import("./src/app/./scan/[token]/page.jsx");
  "__create/not-found": typeof import("./src/app/./__create/not-found.tsx");
};